#!/usr/bin/env python3
# Generated by AI
from __future__ import annotations

import argparse
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

WIKILINK_PATTERN = re.compile(r"(!?)\[\[([^\]]+)\]\]")
HEADING_PATTERN = re.compile(r"^#\s+(.+)$", re.MULTILINE)
TITLE_LINE_PATTERN = re.compile(r"^\s*title\s*:\s*(.+?)\s*$", re.IGNORECASE)
DATE_LINE_PATTERN = re.compile(r"^\s*date\s*:\s*(.+?)\s*$", re.IGNORECASE)
DRAFT_LINE_PATTERN = re.compile(r"^\s*draft\s*:\s*(.+?)\s*$", re.IGNORECASE)
MARKDOWN_IMAGE_PATTERN = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
MARKDOWN_LINK_PATTERN = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")


@dataclass
class Post:
    folder_name: str
    source_md: Path
    title: str
    date: str | None
    slug: str
    permalink: str


@dataclass
class LinkReplacement:
    source_file: Path
    original: str
    replaced: str


def slugify(value: str) -> str:
    text = value.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-")
    return text or "post"


def get_front_matter_block(markdown: str) -> str | None:
    if not markdown.startswith("---\n"):
        return None
    end = markdown.find("\n---\n", 4)
    if end == -1:
        return None
    return markdown[4:end]


def extract_obsidian_title(markdown: str) -> str | None:
    block = get_front_matter_block(markdown)
    if not block:
        return None

    for line in block.splitlines():
        match = TITLE_LINE_PATTERN.match(line)
        if not match:
            continue

        value = match.group(1).strip()
        if not value:
            return None

        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1].strip()

        return value or None

    return None


def extract_obsidian_date(markdown: str) -> str | None:
    block = get_front_matter_block(markdown)
    if not block:
        return None

    for line in block.splitlines():
        match = DATE_LINE_PATTERN.match(line)
        if not match:
            continue

        value = match.group(1).strip()
        return value or None

    return None


def extract_obsidian_draft(markdown: str) -> bool:
    block = get_front_matter_block(markdown)
    if not block:
        return False

    for line in block.splitlines():
        match = DRAFT_LINE_PATTERN.match(line)
        if not match:
            continue

        value = match.group(1).strip().strip('"').strip("'").lower()
        return value in {"true", "yes", "1", "on"}

    return False


def discover_posts(source_root: Path) -> list[Post]:
    posts: list[Post] = []

    for folder in sorted(source_root.iterdir()):
        if not folder.is_dir():
            continue

        english_candidates = sorted(folder.glob("* (EN).md"))
        if not english_candidates:
            continue

        source_md = english_candidates[0]
        raw = source_md.read_text(encoding="utf-8")
        if extract_obsidian_draft(raw):
            continue

        front_matter_title = extract_obsidian_title(raw)
        front_matter_date = extract_obsidian_date(raw)
        heading_match = HEADING_PATTERN.search(raw)
        fallback_title = heading_match.group(1).strip() if heading_match else folder.name.replace("_", " ").strip()
        title = front_matter_title or fallback_title

        slug = slugify(folder.name)
        permalink = f"/{slug}/"
        posts.append(
            Post(
                folder_name=folder.name,
                source_md=source_md,
                title=title,
                date=front_matter_date,
                slug=slug,
                permalink=permalink,
            )
        )

    return posts


def build_alias_map(posts: list[Post]) -> dict[str, Post]:
    alias_map: dict[str, Post] = {}

    for post in posts:
        aliases = {
            post.folder_name,
            post.folder_name.lower(),
            post.slug,
            post.slug.lower(),
            post.source_md.stem,
            post.source_md.stem.lower(),
            post.source_md.stem.replace(" (EN)", ""),
            post.source_md.stem.replace(" (EN)", "").lower(),
        }

        for alias in aliases:
            normalized = normalize_link_target(alias)
            if normalized and normalized not in alias_map:
                alias_map[normalized] = post

    return alias_map


def normalize_link_target(target: str) -> str:
    value = target.strip()
    if not value:
        return ""

    value = value.replace("\\", "/")
    if "/" in value:
        value = value.split("/")[-1]

    value = re.sub(r"\.md$", "", value, flags=re.IGNORECASE)
    value = value.replace(" (EN)", "")
    value = value.replace("_", "-")

    return slugify(value)


def convert_wikilinks(
    markdown: str,
    alias_map: dict[str, Post],
    unresolved: set[str],
    source_file: Path,
    replacements: list[LinkReplacement],
) -> str:
    def replace(match: re.Match[str]) -> str:
        is_embed, raw_inner = match.groups()
        inner = raw_inner.strip()

        if "|" in inner:
            left, right = inner.split("|", 1)
            raw_target = left.strip()
            alias_text = right.strip()
        else:
            raw_target = inner
            alias_text = ""

        if "#" in raw_target:
            target_part, anchor_part = raw_target.split("#", 1)
            anchor_slug = slugify(anchor_part)
            anchor = f"#{anchor_slug}" if anchor_slug else ""
        else:
            target_part = raw_target
            anchor = ""

        normalized = normalize_link_target(target_part)
        post = alias_map.get(normalized)
        if not post:
            unresolved.add(raw_target)
            return match.group(0)

        label = alias_text or target_part.split("/")[-1]
        url = f"{post.permalink}{anchor}"
        replaced = f"[{label}]({url})"
        replacements.append(LinkReplacement(source_file=source_file, original=match.group(0), replaced=replaced))
        return replaced

    def convert_inline_safe(line: str) -> str:
        parts: list[str] = []
        current: list[str] = []
        i = 0
        in_code = False
        fence_len = 0

        while i < len(line):
            ch = line[i]
            if ch == "`":
                tick_start = i
                while i < len(line) and line[i] == "`":
                    i += 1
                ticks = i - tick_start

                if in_code and ticks == fence_len:
                    current.append(line[tick_start:i])
                    parts.append("".join(current))
                    current = []
                    in_code = False
                    fence_len = 0
                elif not in_code:
                    if current:
                        parts.append(WIKILINK_PATTERN.sub(replace, "".join(current)))
                        current = []
                    current.append(line[tick_start:i])
                    in_code = True
                    fence_len = ticks
                else:
                    current.append(line[tick_start:i])
                continue

            current.append(ch)
            i += 1

        if current:
            if in_code:
                parts.append("".join(current))
            else:
                parts.append(WIKILINK_PATTERN.sub(replace, "".join(current)))

        return "".join(parts)

    output: list[str] = []
    in_fence = False
    fence_char = ""
    fence_len = 0

    for line in markdown.splitlines(keepends=True):
        stripped = line.lstrip()

        if not in_fence:
            open_match = re.match(r"^([`~]{3,})", stripped)
            if open_match:
                marker = open_match.group(1)
                in_fence = True
                fence_char = marker[0]
                fence_len = len(marker)
                output.append(line)
                continue

            output.append(convert_inline_safe(line))
            continue

        output.append(line)
        close_match = re.match(r"^([`~]{3,})\s*$", stripped)
        if close_match:
            marker = close_match.group(1)
            if marker[0] == fence_char and len(marker) >= fence_len:
                in_fence = False
                fence_char = ""
                fence_len = 0

    return "".join(output)


def strip_front_matter(markdown: str) -> str:
    if markdown.startswith("---\n"):
        end = markdown.find("\n---\n", 4)
        if end != -1:
            return markdown[end + 5 :]
    return markdown


def rewrite_local_image_links(markdown: str, post: Post) -> str:
    asset_base = f"/published/{post.slug}/"

    def replace(match: re.Match[str]) -> str:
        alt_text, raw_target = match.groups()
        target = raw_target.strip()

        if not target:
            return match.group(0)

        if target.startswith(("http://", "https://", "/", "#", "data:")):
            return match.group(0)

        if " " in target:
            path_part, rest = target.split(" ", 1)
            suffix = f" {rest}"
        else:
            path_part = target
            suffix = ""

        rewritten = f"{asset_base}{path_part}"
        return f"![{alt_text}]({rewritten}{suffix})"

    return MARKDOWN_IMAGE_PATTERN.sub(replace, markdown)


def escape_pipe_in_markdown_link_labels(markdown: str) -> str:
    def escape_links_in_text(text: str) -> str:
        def replace(match: re.Match[str]) -> str:
            label, target = match.groups()
            escaped_label = re.sub(r"(?<!\\)\|", r"\\|", label)
            return f"[{escaped_label}]({target})"

        return MARKDOWN_LINK_PATTERN.sub(replace, text)

    def escape_inline_safe(line: str) -> str:
        parts: list[str] = []
        current: list[str] = []
        i = 0
        in_code = False
        fence_len = 0

        while i < len(line):
            ch = line[i]
            if ch == "`":
                tick_start = i
                while i < len(line) and line[i] == "`":
                    i += 1
                ticks = i - tick_start

                if in_code and ticks == fence_len:
                    current.append(line[tick_start:i])
                    parts.append("".join(current))
                    current = []
                    in_code = False
                    fence_len = 0
                elif not in_code:
                    if current:
                        parts.append(escape_links_in_text("".join(current)))
                        current = []
                    current.append(line[tick_start:i])
                    in_code = True
                    fence_len = ticks
                else:
                    current.append(line[tick_start:i])
                continue

            current.append(ch)
            i += 1

        if current:
            if in_code:
                parts.append("".join(current))
            else:
                parts.append(escape_links_in_text("".join(current)))

        return "".join(parts)

    output: list[str] = []
    in_fence = False
    fence_char = ""
    fence_len = 0

    for line in markdown.splitlines(keepends=True):
        stripped = line.lstrip()

        if not in_fence:
            open_match = re.match(r"^([`~]{3,})", stripped)
            if open_match:
                marker = open_match.group(1)
                in_fence = True
                fence_char = marker[0]
                fence_len = len(marker)
                output.append(line)
                continue

            output.append(escape_inline_safe(line))
            continue

        output.append(line)
        close_match = re.match(r"^([`~]{3,})\s*$", stripped)
        if close_match:
            marker = close_match.group(1)
            if marker[0] == fence_char and len(marker) >= fence_len:
                in_fence = False
                fence_char = ""
                fence_len = 0

    return "".join(output)


def write_post(
    post: Post,
    source_root: Path,
    output_root: Path,
    alias_map: dict[str, Post],
    unresolved: set[str],
    replacements: list[LinkReplacement],
) -> None:
    post_output_dir = output_root / post.slug
    post_output_dir.mkdir(parents=True, exist_ok=True)

    source_folder = post.source_md.parent
    for item in source_folder.iterdir():
        if item == post.source_md:
            continue
        if item.is_file() and item.suffix.lower() == ".md":
            continue
        dest = post_output_dir / item.name
        if item.is_dir():
            shutil.copytree(item, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(item, dest)

    raw = post.source_md.read_text(encoding="utf-8")
    body = strip_front_matter(raw)
    converted = convert_wikilinks(body, alias_map, unresolved, source_file=post.source_md, replacements=replacements)
    converted = escape_pipe_in_markdown_link_labels(converted)
    converted = rewrite_local_image_links(converted, post)
    escaped_title = post.title.replace('"', '\\"')
    date_line = f"date: {post.date}\n" if post.date else ""

    output_md = (
        "---\n"
        "layout: page\n"
        f"title: \"{escaped_title}\"\n"
        f"{date_line}"
        f"permalink: {post.permalink}\n"
        "---\n\n"
        f"{converted.strip()}\n"
    )
    (post_output_dir / "index.md").write_text(output_md, encoding="utf-8")


def write_replacement_report(output_root: Path, replacements: list[LinkReplacement], source_root: Path) -> Path:
    report_path = output_root / "wikilink_replacements.txt"
    lines: list[str] = ["# Wikilink replacement report", ""]

    if not replacements:
        lines.append("No wikilinks were replaced.")
    else:
        for item in replacements:
            try:
                display_source = item.source_file.relative_to(source_root)
            except ValueError:
                display_source = item.source_file
            lines.append(f"- {display_source}: {item.original} -> {item.replaced}")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report_path


def sync(source_root: Path, output_root: Path, clean: bool) -> tuple[int, list[str], Path]:
    if clean and output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    posts = discover_posts(source_root)
    alias_map = build_alias_map(posts)
    unresolved: set[str] = set()
    replacements: list[LinkReplacement] = []

    for post in posts:
        write_post(post, source_root, output_root, alias_map, unresolved, replacements)

    report_path = write_replacement_report(output_root=output_root, replacements=replacements, source_root=source_root)
    return len(posts), sorted(unresolved), report_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Sync only English Obsidian posts (files ending with ' (EN).md') into this "
            "repository for GitHub Pages publishing."
        )
    )
    parser.add_argument(
        "--source",
        default="~/Documents/Obsidian/Blog",
        help="Path to the Obsidian Blog directory (default: ~/Documents/Obsidian/Blog)",
    )
    parser.add_argument(
        "--output",
        default="published",
        help="Output directory inside this repo (default: published)",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not clean output directory before sync",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_root = Path(args.source).expanduser().resolve()
    output_root = Path(args.output).resolve()

    if not source_root.exists() or not source_root.is_dir():
        raise SystemExit(f"Source directory does not exist: {source_root}")

    count, unresolved, report_path = sync(source_root=source_root, output_root=output_root, clean=not args.no_clean)

    print(f"Synced {count} English post(s) to {output_root}")
    print(f"Wikilink replacement report: {report_path}")
    if unresolved:
        print("Unresolved wikilinks:")
        for item in unresolved:
            print(f"  - {item}")


if __name__ == "__main__":
    main()
